USE renatocf;
DROP TABLE gamer;
DROP TABLE team;
DROP TABLE game;
DROP TABLE distributor;
DROP TABLE challenge;
DROP TABLE rel_distribute;
DROP TABLE rel_owns;
DROP TABLE rel_participate;
DROP TABLE rel_play;
DROP TABLE rel_dispute;
